name: wp-app
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    source_dir: /
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm install
    run_command: npm start
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
    health_check:
      http_path: /
    routes:
      - path: /
